name: dartexif
version: 0.1.1
author: Taesu Pyo <pyotaesu@gmail.com>
description: Library of exif.
homepage: https://www.github.com/bigflood/dartexif
environment:
  sdk: '>=1.16.0-dev.5.0 <2.0.0'
dependencies:
  args:
  collection: '^1.0.0'
  convert: '>=1.0.0 <3.0.0'
  sprintf: ">=1.0.8 <2.0.0"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
executables:
  exif:
  