name: exif
version: 1.0.3
author: Taesu Pyo <pyotaesu@gmail.com>
description: Decode Exif data from tiff and jpeg files.
homepage: https://www.github.com/bigflood/dartexif
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  args: ^2.0.0
  collection: ^1.15.0
  convert: ^3.0.0
  sprintf: ^6.0.0
dev_dependencies:
  test: ^1.16.8
  archive: ^3.1.2
  path: ^1.8.0
  http: ^0.13.1
  json_annotation: ^4.0.1
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  stream_channel: ^2.1.0
executables:
  print_exif:
  